FROM golang:1.21.3 as builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY cmd/migrations cmd/migrations
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o migration-service cmd/migrations/main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder /app/migration-service /app/migration-service
COPY migrations /app/migrations
WORKDIR /app
CMD ["./migration-service", "-storage-path=postgres://user:pass@postgres:5432/default", "-migrations-path=./migrations"]